import streamlit as st
import pandas as pd
import plotly.express as px

def show_recommendations():
    st.title("Energy Efficiency Recommendations")
    
    # Check if detection results are available
    if st.session_state.detection_results is None:
        st.info("No detection results available. Please run anomaly detection first.")
        if st.button("Go to Detection Page"):
            st.session_state.current_page = "detection"
            st.rerun()
        return
    
    # Get results from session state
    results = st.session_state.detection_results
    
    # Check if recommendations are available
    if hasattr(st.session_state, 'recommendations') and st.session_state.recommendations:
        recommendations = st.session_state.recommendations
    else:
        # Generate recommendations based on anomalies (simplified version)
        # This is a fallback if the recommendations weren't generated by the API
        anomalies = results[results['anomaly'] == 1]
        anomaly_count = len(anomalies)
        total_count = len(results)
        anomaly_percent = (anomaly_count / total_count) * 100
        
        recommendations = {
            'general': [
                {
                    'title': f"Anomaly Rate: {anomaly_percent:.1f}%",
                    'description': "Based on the anomaly detection results, we've identified patterns in your energy consumption data that could indicate inefficiencies."
                }
            ],
            'specific': [],
            'alerts': []
        }
        
        # Add some general recommendations
        if anomaly_percent > 10:
            recommendations['general'].append({
                'title': 'High Anomaly Rate Detected',
                'description': 'Your system shows a higher than normal rate of anomalies. Consider a thorough energy audit to identify potential issues.'
            })
        else:
            recommendations['general'].append({
                'title': 'Low Anomaly Rate Detected',
                'description': 'Your system shows a relatively low rate of anomalies. Continue monitoring and focus on the specific issues identified.'
            })
        
        # Check if time features are available
        if 'hour' in results.columns:
            # Find the hour with most anomalies
            hour_counts = anomalies['hour'].value_counts().sort_values(ascending=False)
            if not hour_counts.empty:
                peak_hour = hour_counts.index[0]
                peak_count = hour_counts.iloc[0]
                
                recommendations['specific'].append({
                    'title': f'Peak Anomaly Hour: {peak_hour}:00',
                    'description': f'We detected {peak_count} anomalies during the {peak_hour}:00 hour. Consider reviewing equipment operation during this time period.'
                })
        
        # Check if location data is available
        if 'location' in results.columns:
            # Find locations with most anomalies
            location_counts = anomalies['location'].value_counts().sort_values(ascending=False)
            if not location_counts.empty:
                top_location = location_counts.index[0]
                location_count = location_counts.iloc[0]
                
                recommendations['specific'].append({
                    'title': f'Location with Most Anomalies: {top_location}',
                    'description': f'We detected {location_count} anomalies at {top_location} locations. Consider focused monitoring and maintenance for these sites.'
                })
        
        # Add some alerts for highest anomaly scores
        if 'anomaly_score' in anomalies.columns:
            top_anomalies = anomalies.nlargest(3, 'anomaly_score')
            
            for i, (idx, row) in enumerate(top_anomalies.iterrows()):
                alert_desc = f"Anomaly score: {row['anomaly_score']:.2f}"
                
                # Add timestamp if available
                if 'timestamp' in row and pd.notna(row['timestamp']):
                    alert_desc += f" at {row['timestamp']}"
                
                # Add consumption if available
                if 'consumption' in row:
                    alert_desc += f", consumption: {row['consumption']:.2f}"
                
                recommendations['alerts'].append({
                    'title': f'High Severity Anomaly #{i+1}',
                    'description': alert_desc
                })
    
    # Display recommendations
    st.markdown("### Actionable Recommendations Based on Anomaly Detection")
    
    # General recommendations
    st.markdown("#### General Recommendations")
    
    for i, rec in enumerate(recommendations.get('general', [])):
        with st.expander(rec['title'], expanded=True):
            st.markdown(rec['description'])
    
    # Specific recommendations
    if recommendations.get('specific', []):
        st.markdown("#### Specific Recommendations")
        
        for i, rec in enumerate(recommendations.get('specific', [])):
            with st.expander(rec['title'], expanded=True):
                st.markdown(rec['description'])
    
    # Alerts
    if recommendations.get('alerts', []):
        st.markdown("#### Priority Alerts")
        
        for i, alert in enumerate(recommendations.get('alerts', [])):
            with st.expander(alert['title'], expanded=True):
                st.markdown(alert['description'])
    
    # Visualize anomalies by category if time features are available
    if 'hour' in results.columns and len(results[results['anomaly'] == 1]) > 0:
        st.markdown("### Anomaly Distribution by Time of Day")
        
        # Aggregate anomalies by hour
        anomalies_by_hour = results[results['anomaly'] == 1].groupby('hour').size().reset_index(name='count')
        
        # Create bar chart
        fig = px.bar(
            anomalies_by_hour,
            x='hour',
            y='count',
            title='Anomalies by Hour of Day',
            template='plotly_dark',
            color='count',
            color_continuous_scale='Viridis'
        )
        
        fig.update_layout(
            xaxis_title='Hour of Day',
            yaxis_title='Number of Anomalies',
            xaxis=dict(tickmode='linear', tick0=0, dtick=1),
            height=400
        )
        
        st.plotly_chart(fig, use_container_width=True)
        
        # Add time-based recommendations
        morning_anomalies = anomalies_by_hour[(anomalies_by_hour['hour'] >= 6) & (anomalies_by_hour['hour'] < 12)]['count'].sum()
        afternoon_anomalies = anomalies_by_hour[(anomalies_by_hour['hour'] >= 12) & (anomalies_by_hour['hour'] < 18)]['count'].sum()
        evening_anomalies = anomalies_by_hour[(anomalies_by_hour['hour'] >= 18) & (anomalies_by_hour['hour'] < 22)]['count'].sum()
        night_anomalies = anomalies_by_hour[(anomalies_by_hour['hour'] >= 22) | (anomalies_by_hour['hour'] < 6)]['count'].sum()
        
        time_periods = {
            'Morning (6AM-12PM)': morning_anomalies,
            'Afternoon (12PM-6PM)': afternoon_anomalies,
            'Evening (6PM-10PM)': evening_anomalies,
            'Night (10PM-6AM)': night_anomalies
        }
        
        # Get time period with most anomalies
        peak_period = max(time_periods.items(), key=lambda x: x[1])
        
        st.markdown(f"#### Time-Based Recommendation")
        
        if peak_period[1] > 0:
            with st.expander(f"Most Anomalies Occur During {peak_period[0]}", expanded=True):
                st.markdown(f"""
                We detected {peak_period[1]} anomalies during {peak_period[0]}. 
                
                **Recommended Actions:**
                * Review equipment operation schedules during this time period
                * Check for unnecessary energy usage during {peak_period[0].lower()}
                * Consider adjusting HVAC or lighting settings for this time period
                * Implement automated controls for equipment during these hours
                """)
    
    # Efficiency improvement section
    st.markdown("### Efficiency Improvement Potential")
    
    # Calculate potential savings
    if 'consumption' in results.columns and 'anomaly' in results.columns:
        normal_mean = results[results['anomaly'] == 0]['consumption'].mean()
        anomaly_mean = results[results['anomaly'] == 1]['consumption'].mean()
        
        if anomaly_mean > normal_mean:
            excess = anomaly_mean - normal_mean
            potential_savings = excess * len(results[results['anomaly'] == 1])
            total_consumption = results['consumption'].sum()
            savings_percent = (potential_savings / total_consumption) * 100
            
            col1, col2 = st.columns(2)
            
            with col1:
                st.metric("Potential Energy Savings", f"{potential_savings:.2f} kWh")
            
            with col2:
                st.metric("Percentage of Total Consumption", f"{savings_percent:.2f}%")
            
            # Add efficiency recommendation
            st.markdown("#### Efficiency Recommendation")
            
            with st.expander("Energy Savings Opportunity", expanded=True):
                st.markdown(f"""
                By addressing the detected anomalies, you could potentially save {potential_savings:.2f} kWh, 
                which represents {savings_percent:.2f}% of your total energy consumption.
                
                **Action Plan:**
                1. Focus on the time periods and locations with the highest anomaly rates
                2. Implement the specific recommendations provided above
                3. Monitor results after making changes
                4. Continue regular anomaly detection to identify new opportunities
                """)
    
    # Download recommendations
    st.markdown("### Download Recommendations")
    
    if st.button("Download Recommendations Report"):
        # Generate recommendations report
        report = "# Energy Efficiency Recommendations Report\n\n"
        
        report += "## General Recommendations\n\n"
        for rec in recommendations.get('general', []):
            report += f"### {rec['title']}\n"
            report += f"{rec['description']}\n\n"
        
        if recommendations.get('specific', []):
            report += "## Specific Recommendations\n\n"
            for rec in recommendations.get('specific', []):
                report += f"### {rec['title']}\n"
                report += f"{rec['description']}\n\n"
        
        if recommendations.get('alerts', []):
            report += "## Priority Alerts\n\n"
            for alert in recommendations.get('alerts', []):
                report += f"### {alert['title']}\n"
                report += f"{alert['description']}\n\n"
        
        report += "\n\n© 2025 Opulent Chikwiramakomo. All rights reserved."
        
        st.download_button(
            label="Download Report",
            data=report,
            file_name="energy_efficiency_recommendations.md",
            mime="text/markdown"
        )
