[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000
enableXsrfProtection = false

[browser]
serverAddress = "localhost"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"